<a href="https://colab.research.google.com/github/INDHUJA007-HUB/indhuja-day15-workshop/blob/main/Day5/Day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#import all dependenices

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [5]:
#Scikit learn Python's standard ML library(pre-installed in colab)

from sklearn.model_selection import train_test_split
# train_test_split divides the data into training and testing data

from sklearn.preprocessing import LabelEncoder,StandardScaler
# Label Encoder is uses to change the categorical data into numerical value It is starts with {0}
#StandardScalar : scalar numbers so all features have same range

from sklearn.linear_model import LinearRegression
# Linearregression : fits a straight line relationship between features and target

from sklearn.tree import DecisionTreeRegressor
# Decision tree regressors : builds an tree if/else rules to predict

from sklearn.ensemble import RandomForestRegressor
#RandomforestRegressors : builds 100 decision trees and give an average prediction

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
# mean_absolute_error : average absolute error for prediction
#mean_squared_error : average squarerd error  (penalities for large mistakes)
# r2_score : 0.0 to 1.0 qualtiy score (1.0 is prefect)

print("All Libraries are imported successfully")

All Libraries are imported successfully

In [7]:
## step 2 : load the  student dataset

df=pd.read_csv('/content/drive/MyDrive/DAY 1/student_performance.csv')
print(f'Dataset loaded:{df.shape[0]} students,{df.shape[1]}')
print(f'Columns list{df.columns.tolist()}')
df.head(5)

Dataset loaded:30 students,13
Columns list['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [10]:
# step 3 missing values

print(f'Missing values{df.isnull().sum()}')
print(f'Total missing vales in whole dataset {df.isnull().sum().sum()}')

Missing valuesstudent_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64
Total missing vales in whole dataset 0

In [12]:
df_ml=df.copy()
le_gender = LabelEncoder()
df_ml['gender_encoder']=le_gender.fit_transform(df_ml['gender'])
print(f'Gender Encoding:{dict(zip(le_gender.classes_,le_gender.transform(le_gender.classes_)))}')
le_dept = LabelEncoder()
df_ml['dept_encoder']=le_dept.fit_transform(df_ml['department'])
print(f'Department Encoding:{dict(zip(le_dept.classes_,le_dept.transform(le_dept.classes_)))}')
print('\nNew Columns added in an dataset: dept_encoder,gender_encoder')
df_ml[['gender','gender_encoder','department','dept_encoder']].head(5)

Gender Encoding:{'Female': np.int64(0), 'Male': np.int64(1)}
Department Encoding:{'Civil': np.int64(0), 'Computer Science': np.int64(1), 'Electronics': np.int64(2), 'Mechanical': np.int64(3)}

New Columns added in an dataset: dept_encoder,gender_encoder

   gender  gender_encoder        department  dept_encoder
0    Male               1  Computer Science             1
1  Female               0  Computer Science             1
2    Male               1       Electronics             2
3  Female               0        Mechanical             3
4    Male               1  Computer Science             1

In [18]:
# feature selection

features_col=[
    'math_score',
    'science_score',
    'english_score',
    'attendance_percentage',
    'gender_encoder',
    'dept_encoder'
]
X=df_ml[features_col]
y=df_ml['programming_score']

print(f'Feature Matrix X shape:{X.shape} (Students*features)')
print(f'Target Vector y shape:{y.shape}(one score per student)')
print(f'\nFeatures columns{features_col}')
print(f'Target Column:Programming score')
print(f'\nTarget Range: {y.min()} to {y.max()} (mean: {y.mean():.1f})')

Feature Matrix X shape:(30, 6) (Students*features)
Target Vector y shape:(30,)(one score per student)

Features columns['math_score', 'science_score', 'english_score', 'attendance_percentage', 'gender_encoder', 'dept_encoder']
Target Column:Programming score

Target Range: 38 to 97 (mean: 67.6)

In [21]:
# step 6 -Train/Test split

X_train,X_test,y_train,y_test=train_test_split(
    X,y,
  test_size=0.2,
  random_state=42)

print(f'Total Students:{len(X)}')
print(f'Traning Students:{len(X_train)} ({len(X_train)/len(X) *100:.0f}%)')
print(f'Testing Students:{len(X_test)} ({len(X_test)/len(X) *100:.0f}%)')
print(f'\nTraning target range:{len(y_train)} ({len(y_train)/len(y) *100:.0f}%)')
print(f'Testing target range:{len(y_test)} ({len(y_test)/len(y) *100:.0f}%)')
print(f'\nTraning target range: {y_train.min()} - {y_train.max()}')
print(f'Testing target range: {y_test.min()} - {y_test.max()}')

Total Students:30
Traning Students:24 (80%)
Testing Students:6 (20%)

Traning target range:24 (80%)
Testing target range:6 (20%)

Traning target range: 38 - 96
Testing target range: 39 - 97

In [27]:
le_standard = StandardScaler()
X_train_scaled=le_standard.fit_transform(X_train)
X_test_scaled=le_standard.transform(X_test)

print(f'Features scaled successfully!!')
print(f'Traning feature mean (should be =0): {X_train_scaled.mean():.4f}')
print(f'Traning feature std (should be =1): {X_train_scaled.std():.4f}')
print('\nNote: Scalar was fit on traning data only-prevents data leakage')

Features scaled successfully!!
Traning feature mean (should be =0): -0.0000
Traning feature std (should be =1): 1.0000

Note: Scalar was fit on traning data only-prevents data leakage

In [30]:
# Train Model 1:Linear Regression

lr_model = LinearRegression()
lr_model.fit(X_train_scaled,y_train)
lr_pred=lr_model.predict(X_test_scaled)

#evaluate
lr_mean= mean_absolute_error(y_test,lr_pred)
lr_rmse=np.sqrt(mean_squared_error(y_test,lr_pred))
lr_r2=r2_score(y_test,lr_pred)

print('=== Model 1: Linear Regression ===')
print(f'Mean Absolute Error:{lr_mean:.2f} (prediction are off by{lr_mean:.1f} poinys on average)')
print(f'RMSE:{lr_rmse:.2f} (error with penalty for large mistakes)')
print(f'R^2: {lr_r2:.4f} ({lr_r2*100:.1f}% of programming score variation explained)')
print()
print('Learned coefficients (importance of each feature):')
for feat, coef in zip(features_col, lr_model.coef_):
  print(f'{feat}: {coef:+.3f}')
print(f'Bias (intercept): {lr_model.intercept_:.3f}')

=== Model 1: Linear Regression ===
Mean Absolute Error:9.37 (prediction are off by9.4 poinys on average)
RMSE:11.47 (error with penalty for large mistakes)
R^2: 0.7356 (73.6% of programming score variation explained)

Learned coefficients (importance of each feature):
math_score: +20.256
science_score: +7.612
english_score: +2.396
attendance_percentage: -12.886
gender_encoder: -0.397
dept_encoder: -0.449
Bias (intercept): 68.042

In [31]:
# decision tree

dt_model=DecisionTreeRegressor(
    max_depth=5,
    random_state=42
)
dt_model.fit(X_train_scaled,y_train)
dt_pred=dt_model.predict(X_test_scaled)
dt_mean=mean_absolute_error(y_test,dt_pred)
dt_rmse=np.sqrt(mean_absolute_error(y_test,dt_pred))
dt_r2=r2_score(y_test,dt_pred)
print('=== Model 2: Decision Tree ===')
print(f'Mean Absolute Error:{dt_mean:.2f} ')
print(f'RMSE:{dt_rmse:.2f} ')
print(f'R^2: {dt_r2:.4f} ')

=== Model 2: Decision Tree ===
Mean Absolute Error:10.75
RMSE:3.28
R^2: 0.4803

In [32]:
#RandomforestRegressor

rf_model=RandomForestRegressor(
    max_depth=5,
    random_state=42
)
rf_model.fit(X_train_scaled,y_train)
rf_pred=rf_model.predict(X_test_scaled)
rf_mean=mean_absolute_error(y_test,rf_pred)
rf_rmse=np.sqrt(mean_absolute_error(y_test,rf_pred))
rf_r2=r2_score(y_test,rf_pred)
print('=== Model 2: RandomFOrest Regressor ===')
print(f'Mean Absolute Error:{rf_mean:.2f} ')
print(f'RMSE:{rf_rmse:.2f} ')
print(f'R^2: {rf_r2:.4f} ')

=== Model 2: RandomFOrest Regressor ===
Mean Absolute Error:10.59
RMSE:3.25
R^2: 0.6043